name: Build and Trigger Deployment

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Specify the .NET 8 version you are targeting

    - name: Restore dependencies
      run: dotnet restore Celestio.sln

    - name: Build
      run: dotnet build Celestio.sln --configuration Debug --no-restore

    # - name: Test # Optionally, run your unit tests
    #   run: dotnet test Celestio.sln --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish Celestio.Api/Celestio.Api.csproj -c Debug -o ./publish --no-restore
      # Make sure to adjust the path to your .csproj file

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Deployment Workflow in Infrastructure Repository
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Celestio-dev/Celestio.Infrastructure/dispatches \
          -d '{"event_type": "deploy-test-environment", "client_payload": {"ref": "refs/heads/test", "sha": "${{ github.sha }}"} }'
