name: Build and Trigger Deployment

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrCelestioTest.azurecr.io
        username: ${{ secrets.AZURE_ACR_CREDENTIALS_USERNAME }}
        password: ${{ secrets.AZURE_ACR_CREDENTIALS_PASSWORD }}

    - name: Build and push image
      run: |
        IMAGE_TAG=${GITHUB_REF#refs/tags/}
        docker build . -t acrCelestioTest.azurecr.io/celestio.api:${IMAGE_TAG}
        docker push acrCelestioTest.azurecr.io/celestio.api:${IMAGE_TAG}
        
        # Optionally, also tag and push as 'latest' or 'test'
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          docker tag acrCelestioTest.azurecr.io/celestio.api:${IMAGE_TAG} acrCelestioTest.azurecr.io/Celestio.Api:latest
          docker push acrCelestioTest.azurecr.io/celestio.api:latest
        fi

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Deployment Workflow in Infrastructure Repository
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Celestio-dev/Celestio.Infrastructure/dispatches \
          -d '{"event_type": "deploy-test-environment", "client_payload": {"ref": "refs/heads/test", "sha": "${{ github.sha }}"} }'
