name: Build and Trigger Deployment

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Add steps to build your .NET Web API
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    # - name: Build
    #   run: dotnet build YourSolution.sln --configuration Release

    # This is a placeholder step. Replace with your actual build steps.

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Trigger Deployment Workflow in Infrastructure Repository
      uses: mvasigh/dispatch-action@v1
      with:
        token: ${{ secrets.PULUMI_PERSONAL_ACCESS_TOKEN }}
        repo: Celestio-dev/Celestio.Infrastructure
        event_type: deploy-test-environment
        client_payload: '{"ref":"refs/heads/test","sha":"${{ github.sha }}"}'
