name: Build and Trigger Deployment

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Specify the .NET 8 version you are targeting

    - name: Restore dependencies
      run: dotnet restore Celestio.sln

    - name: Build
      run: dotnet build Celestio.sln --configuration Debug --no-restore

    # - name: Test # Optionally, run your unit tests
    #   run: dotnet test Celestio.sln --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish Celestio.Api/Celestio.Api.csproj -c Debug -o ./publish --no-restore
      # Make sure to adjust the path to your .csproj file

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Trigger Deployment Workflow in Infrastructure Repository
      uses: mvasigh/dispatch-action@v1
      with:
        token: ${{ secrets.PULUMI_PERSONAL_ACCESS_TOKEN }}
        repo: Celestio-dev/Celestio.Infrastructure
        event_type: deploy-test-environment
        client_payload: '{"ref":"refs/heads/test","sha":"${{ github.sha }}"}'
